### ISSUE TITLE
"Rich" package missing from requirements

### ISSUE THREAD

**Issue by kpertsch** [mees/calvin_env#2]
After running the installation as per the instructions, the `play_table_env.py` file throws an error since it imports from the "rich" package, which is not part of `requirements.txt`. Can be manually fixed via `pip install rich`, but would be good to include "rich" in the `requirements.txt` file.

(note that I installed the environment without the "calvin_models" package, ie only "calvin_env")

**Comment by mees** [comment]
Thanks @kpertsch good catch!
