### ISSUE TITLE
Different in `use_egl` or not

### ISSUE THREAD

**Issue by zcczhang** [mees/calvin_env#3]
Hi, I am playing with calvin env and found the evaluation with `use_egl=True` and `use_egl=False` have a big difference: the evaluation with egl (so GPU) will provide reasonable accuracies, but when I turned `use_egl=False`, the evaluation results became much much worse. Also, the table in rendering also has a little different. Therefore, I am wondering if there's anything missing or if this is expected. Thanks!

**Comment by lukashermann** [comment]
This is to be expected. If you do not use egl (i.e. not rendering on GPU but on CPU), it uses a different renderer and the observation looks different. Not drastically different, but noticeable (btw the same would happen if you use the GUI).
If you use `cv2.imshow` to draw the observation you can see it yourself.

What do you mean with "Also, the table in rendering also has a little different."?

**Comment by zcczhang** [comment]
I see, this makes sense. Thank you to clarify! I just would like to say the textures of the tables in calvin are a little different with the same code but different renderer. Even so, is there any workaround that can resolve this? I am just thinking instead of using a dataset generated by egl, but CPU only to train?

**Comment by mees** [comment]
If I understand correctly, yes, each environment has slightly different
looking textures.

**Comment by lukashermann** [comment]
There is no workaround as far as I know. Is there a reason you want to use a different renderer for training?

**Comment by zcczhang** [comment]
well, I'd like to parallel envs for rollout evaluations, and if envs are rendered in GPU, that is somewhat I don't think possible to use vector envs (either constraint by RAM, and even some constraint for going over GPUs for some servers)?

**Comment by lukashermann** [comment]
You can use vector envs if you run them in subprocesses (like [this](https://stable-baselines.readthedocs.io/en/master/guide/vec_envs.html)), depending on how much space your GPU has. Also, the CPU renderer is much slower than the GPU renderer, so you would probably not gain a speed up anyway even if you parallelize it.

**Comment by zcczhang** [comment]
yeah this is what I'd like to try. And yes, I observed the much slower performance in CPU as well. Thank you!
