### ISSUE TITLE
Major concern about evaluation

### ISSUE THREAD

**Issue by ezhang7423** [mees/calvin_env#5]
Hi there!
I've found that rolling out ground truth trajectories (labelled by the language annotator) from the dataset is not always evaluated to be successful by the `Tasks.get_task_info`. This seems to be quite concerning. Perhaps I've done something wrong on my end?

![image](https://user-images.githubusercontent.com/54998055/207159778-2dda7025-5b14-4b5a-b9ed-453f144adea7.png)

**Comment by lukashermann** [comment]
Could you share which code you ran exactly?

**Comment by lukashermann** [comment]
And could I ask you to move (i.e. reopen) this issue to the [calvin](https://github.com/mees/calvin) repo?

**Comment by ezhang7423** [comment]
Sorry for the late reply! I've attached info to reproduce in this issue: https://github.com/mees/calvin/issues/32
